### ISSUE TITLE
error 500 on http://invesdwin.de/artifactory/invesdwin-oss-remote

### ISSUE THREAD

**Issue by akuma8** [invesdwin/invesdwin-instrument#10]
Hi, 
The repository is unavailable, I am getting an error 500 when I build my porject with maven. 
When I visit the repo url, I got this:
```

{
  "errors" : [ {
    "status" : 500,
    "message" : "Artifactory failed to initialize: check Artifactory logs for errors."
  } ]
}

```

**Comment by subes** [comment]
Thanks for the info. It seems the upgrade did not restart artifactory properly. I fixed it manually.
