### ISSUE TITLE
Failed to read artifact descriptor for de.invesdwin:invesdwin-instrument:jar:1.0.2

### ISSUE THREAD

**Issue by andreas-wolf** [invesdwin/invesdwin-instrument#11]
`{
errors: [
{
status: 500,
message: "HTTP response status 401:Failed on executing /api/v1/users/anonymous, with response: { "errors" : [ { "code" : "UNAUTHORIZED", "message" : "Bearer authentication failed", "detail" : "invalid token" } ] }"
}
]
}`

**Comment by subes** [comment]
Thanks for the notification, there was a jdbc issue caused by a mysql upgrade. Fixed it now. The artifacts should be available again now.
