### ISSUE TITLE
Any plan on hosting this artifact on https?

### ISSUE THREAD

**Issue by mrtinkz** [invesdwin/invesdwin-instrument#12]
Thanks for this fantastic library, any plans on hosting this artifact on https? currently it's difficult to download this dependency since it's on http while being on a corporate proxy.

http://invesdwin.de/artifactory/invesdwin-oss-remote

**Comment by subes** [comment]
https://invesdwin.de/artifactory/invesdwin-oss-remote is now working as well via LetsCrypt

**Comment by mrtinkz** [comment]
Thank you
