### ISSUE TITLE
Any plan on deploy this artifact to maven repository?

### ISSUE THREAD

**Issue by luckypolaris** [invesdwin/invesdwin-instrument#17]
Any plan on deploy this artifact to public maven repository?

**Comment by luckypolaris** [comment]
I mean maven central repo

**Comment by subes** [comment]
Thanks for the suggestion, but currently this is not planned. 

Adding another repository inside a pom.xml: 
```
<repositories>
	<repository>
		<id>invesdwin-oss</id>
		<url>https://invesdwin.de/repo/invesdwin-oss-remote</url>
	</repository>
</repositories>
<pluginRepositories>
	<pluginRepository>
		<id>invesdwin-oss</id>
		<url>https://invesdwin.de/repo/invesdwin-oss-remote</url>
	</pluginRepository>
</pluginRepositories>
```

Or adding it in your settings.xml
https://devcenter.heroku.com/articles/using-a-custom-maven-settings-xml

or installing your own proxy nexus-oss/artifactory-oss server are options to integrate the repository.

**Comment by luckypolaris** [comment]
Thanks for reply , Got it

**Comment by paulvi** [comment]
Thanks to Edwin @subes for linking issues like https://github.com/invesdwin/invesdwin-scripting/issues/6

This issue seems to be complicated.

**Comment by Noah1989** [comment]
Seems like invesdwin.de is down right now :(

**Comment by jaletechs** [comment]
> Seems like invesdwin.de is down right now :(

Sadly, just cleared my .m2 and my application is stuck trying to download the dependency.

**Comment by subes** [comment]
Server is up again. Was not able to restart yesterday because I was in rain with the motorbike at nordkapp/norway.

**Comment by jaletechs** [comment]
Thanks! I was able to build about 30 minutes ago.

**Comment by stefanrybacki** [comment]
> Server is up again. Was not able to restart yesterday because I was in rain with the motorbike at nordkapp/norway.

That is the reason why it should be on maven central, though.

**Comment by jaletechs** [comment]
Seems to be down again
