### ISSUE TITLE
Why aren't artifacts published to maven-central?

### ISSUE THREAD

**Issue by andreak** [invesdwin/invesdwin-instrument#18]

**Comment by subes** [comment]
See answer here: https://github.com/invesdwin/invesdwin-instrument/issues/17

**Comment by andreak** [comment]
I know about "local nexus" etc. and have done that, just curious why this isn't published to central as default, are there any extra "painful" steps involved?

**Comment by subes** [comment]
If you want you can publish this artifact yourself to maven central, though official releases will stay on the self hosted repo.

**Comment by andreak** [comment]
Ok
